resolver: lts-7.14
extra-deps: []
flags: {}
extra-package-dbs: []
packages:
- location: .
#- location:
#    git: git@github.com:lancelet/http-proxy.git
#    commit: 3a90265a0536bfc18ca831ea37fb331d051b688a
